name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Backend Docker image
      run: docker build . --file dockerfiles/backend.Dockerfile --tag tayin-backend:$(date +%s)
      
    - name: Test Backend Docker image
      run: docker run --rm tayin-backend:$(date +%s) echo "Backend build successful"

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Frontend Docker image
      run: docker build . --file dockerfiles/frontend.Dockerfile --tag tayin-frontend:$(date +%s)
      
    - name: Test Frontend Docker image
      run: docker run --rm tayin-frontend:$(date +%s) echo "Frontend build successful"

  build-compose:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Docker Compose
      run: docker-compose build
      
    - name: Test Docker Compose
      run: docker-compose config
